baseURL = "https://preforma.se/"
languageCode = "sv"
title = "Preforma Samtalsterapi"
theme = "preforma-theme"

[outputs]
home = [ "HTML", "RSS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[menu]
[[menu.main]]
  name = "Start"
  identifier = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tjänster"
  identifier = "tjanster"
  url = "/tjanster/"
  weight = 2

[[menu.main]]
  name = "Hur går det till?"
  identifier = "hur-gar-det-till"
  url = "/hur-gar-det-till/"
  weight = 3

[[menu.main]]
  name = "Boka"
  identifier = "boka"
  url = "/boka/"
  weight = 4
