baseURL = "https://nervous-sinoussi-e114f9.netlify.com/"
languageCode = "sv"
title = "Preforma Samtalsterapi"
theme = "preforma-theme"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "\.(ttf|otf|eot|woff|woff2)$"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[outputs]
home = [ "HTML", "RSS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[menu]
[[menu.main]]
  name = "Start"
  identifier = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Terapi"
  identifier = "terapi"
  url = "/terapi/"
  weight = 2

[[menu.main]]
  name = "Om Kim"
  identifier = "om-kim"
  url = "/om-kim/"
  weight = 3

[[menu.main]]
  name = "Boka"
  identifier = "boka"
  url = "/boka/"
  weight = 4
