baseURL = "https://nervous-sinoussi-e114f9.netlify.com/"
languageCode = "sv"
title = "Preforma Samtalsterapi"
theme = "preforma-theme"

[outputs]
home = [ "HTML", "RSS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
