baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "preforma-theme"

[outputs]
home = [ "HTML", "RSS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
