backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
    - label: "Pages"
      name: "pages"
      format: "toml-frontmatter"
      frontmatter_delimiter: "+++"
      files:
        - label: "Home Page"
          name: "home"
          file: "content/_index.md"
          fields:
            - {label: "Announcement", name: "announcementText", widget: "markdown"}
            - {label: "Announcement Date", name: "announcementDate", widget: "date"}
